#!/bin/sh

#
# NOTE:  Strictly speaking we DON'T need this file here in the stream package!
# It's here as a prototype.  We DO need it in the sender package so that senders
# can cluster and communicate in Akka.
#

#!/bin/sh

realpath () {
(
  TARGET_FILE="$1"

  cd "$(dirname "$TARGET_FILE")"
  TARGET_FILE=$(basename "$TARGET_FILE")

  COUNT=0
  while [ -L "$TARGET_FILE" -a $COUNT -lt 100 ]
  do
      TARGET_FILE=$(readlink "$TARGET_FILE")
      cd "$(dirname "$TARGET_FILE")"
      TARGET_FILE=$(basename "$TARGET_FILE")
      COUNT=$(($COUNT + 1))
  done

  if [ "$TARGET_FILE" == "." -o "$TARGET_FILE" == ".." ]; then
    cd "$TARGET_FILE"
    TARGET_FILEPATH=
  else
    TARGET_FILEPATH=/$TARGET_FILE
  fi

  echo "$(pwd -P)/$TARGET_FILE"
)
}

real_script_path="$(realpath "$0")"
app_home="$(realpath "$(dirname "$real_script_path")")"
lib_dir="$(realpath "${app_home}/../lib")"

${{template_declares}}

# Custom add here to set env vars and fire up portster to access externaly mapped pors inside Docker
export DOCKER_CERT_PATH="/mnt/certs"
export DOCKER_HOST="tcp://$HOST_IP:2376"
/usr/local/bin/portster &

java -classpath $app_classpath $app_mainclass $@
